services:
  - type: web
    name: intelligence-os-backend
    env: python
    buildCommand: "pip install -r src/backend/requirements-minimal.txt"
    startCommand: "cd src/backend && python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: intelligence-os-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: intelligence-os-redis
          property: connectionString

  - type: web
    name: intelligence-os-frontend
    env: static
    buildCommand: "cd src/frontend && npm ci && npm run build"
    staticPublishPath: src/frontend/dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://intelligence-os-backend.onrender.com/api/*

databases:
  - name: intelligence-os-db
    databaseName: intelligence_os
    user: intelligence_user

  - name: intelligence-os-redis
    type: redis